# --- !Ups

CREATE TABLE "USER" (
    "KEY" INTEGER NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "SURNAME" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    "PASSWORD" VARCHAR NOT NULL,
    "STREET" VARCHAR,
    "CITY" VARCHAR,
    "PHONE" INTEGER,
    "BIRTHDATE" INTEGER
    );

# --- !Downs

DROP TABLE "USER";