# --- !Ups

CREATE TABLE "USER" (
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "SURNAME" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    "PASSWORD" VARCHAR NOT NULL,
    "STREET" VARCHAR,
    "CITY" VARCHAR,
    );

# --- !Downs

DROP TABLE "USER";